[tasks.watch]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-c", "-d", "1.5", "-w", "src", "-x", "run"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-unknown-linux-musl"]
