name: CI

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/ci.yaml"
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/ci.yaml"

jobs:
  check:
    name: Lint and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - beta
          - nightly
        target:
          - x86_64-unknown-linux-musl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install musl-tools package
        if: ${{ matrix.target }} == 'x86_64-unknown-linux-musl'
        run: sudo apt install musl-tools

      - name: Install ${{ matrix.toolchain }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          default: true
          override: true
          profile: default

      - name: Run clippy linter
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload built binary
        uses: actions/upload-artifact@v3
        with:
          name: discorss (${{ matrix.toolchain }}-${{ matrix.target }} build)
          path: target/x86_64-unknown-linux-musl/release/discorss
